name: camitax
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - centrifuge=1.0.3
  - checkm-genome=1.0.11-1
  - bioconductor-dada2=1.6.0
  - kaiju=1.6.2
  - mash=2.0
  - prodigal=2.6.3
